-- 코드를 입력하세요
# SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE') AS TLNO FROM PATIENT WHERE GEND_CD = "W" AND AGE <= 12 ORDER BY AGE DESC, PT_NAME;

SELECT PT_NAME, PT_NO, GEND_CD, AGE, IF(TLNO IS NULL,'NONE',TLNO) AS TLNO FROM PATIENT WHERE GEND_CD = "W" AND AGE <= 12 ORDER BY AGE DESC, PT_NAME;

# SELECT PT_NAME, PT_NO, GEND_CD, AGE,
#     CASE
#         WHEN TLNO IS NULL THEN 'NONE'
#         ELSE TLNO
#     END
# AS TLNO
# FROM PATIENT
# WHERE AGE <= 12 AND GEND_CD = 'W'
# ORDER BY AGE DESC, PT_NAME;